"""
analytics.py
============
Core mathematical analytics engine for the MLB Handicapping System v4.1.

Integrates:
  1. 4-Day Historical Calibration Engine (H-4 to H-1 performance logging)
  2. Recalibrated Moneyline Engine & Bet Slip Suite (2-Leg Anchor, 3-Leg, 4-Leg, 3-of-5 Combo, 5-Leg, 6-Leg, 8-Leg Ultimate)
  3. Strategi 1: Parlay "Under 0.5 Home Run" (3, 4, 5, 8, 10 Legs)
  4. Strategi 2: Parlay / Single "Under 1.5 Hits" (Single Bets vs 2-Team Parlays)
  5. Strategi 3: Alternate Team Total "Over 1.5 Runs" Screener
  6. Strategi 4: At-Bat Outcome "Out or Error" ($100/day system targets)
  7. Strategi 5: 5-Factor Total Score Projection (Over/Under)
"""

from __future__ import annotations

import itertools
import logging
from dataclasses import dataclass, field

import config

logger = logging.getLogger(__name__)


# ==============================================================================
# DATA MODELS — CALIBRATION ENGINE
# ==============================================================================

@dataclass
class CalibrationReport:
    """Report generated by the 4-Day Historical Calibration Engine."""
    lookback_days: int
    total_games_analyzed: int
    avg_error_rate: float
    bullpen_volatility_score: float
    pitcher_whip_accuracy: float
    calibrated_pitcher_weight: float
    calibrated_form_weight: float
    calibrated_ops_weight: float
    calibration_log: list[str] = field(default_factory=list)


# ==============================================================================
# DATA MODELS — STRATEGY A (Moneyline & Bet Slip Suite)
# ==============================================================================

@dataclass
class MoneylineCandidate:
    team_id: int
    team_name: str
    is_home: bool
    game_id: object
    pitcher_name: str
    opponent_team: str
    opponent_pitcher: str

    moneyline_american: int
    moneyline_decimal: float
    best_sportsbook: str
    best_line_american: int

    era_advantage: float
    whip_advantage: float
    our_whip: float
    last3_era: float
    last10_win_rate: float
    ops_advantage_pct: float

    implied_prob: float
    model_prob: float
    win_confidence: float

    trust_level: str          # "HIGH", "MEDIUM", "PASS"
    is_strong_recommendation: bool
    is_qualified: bool
    is_live_data: bool


@dataclass
class MoneylineSlip:
    legs: list[MoneylineCandidate]
    n_legs: int
    combined_confidence: float
    combined_decimal_odds: float
    combined_american_odds: int
    implied_probability: float
    ev_edge: float
    slip_label: str = ""      # e.g. "2-Leg Anchor", "8-Leg Ultimate"


@dataclass
class BetSlipSuite:
    """Complete 7-type bet slip suite generated from ranked candidates."""
    anchor_2leg: MoneylineSlip | None       # Rank 1 + 2
    parlay_3leg: MoneylineSlip | None       # Rank 1-3
    parlay_4leg: MoneylineSlip | None       # Rank 1-4
    combo_3of5:  list[MoneylineSlip]        # All C(5,3) combos from top-5
    parlay_5leg: MoneylineSlip | None       # Rank 1-5
    parlay_6leg: MoneylineSlip | None       # Rank 1-6
    ultimate_8leg: MoneylineSlip | None     # Rank 1-8 (Test Luck)


@dataclass
class LockOfDay:
    candidate: MoneylineCandidate
    rationale: str
    stake_label: str = "1.00 Unit — Lock of the Day / Single Pick"


# ==============================================================================
# DATA MODELS — PROPS STRATEGIES (B1 to B4)
# ==============================================================================

@dataclass
class BatterUnderHRCandidate:
    batter_id: int
    batter_name: str
    team: str
    pitcher_id: int
    pitcher_name: str
    career_pa_vs_pitcher: int
    career_hr_vs_pitcher: int
    season_hr: int
    season_pa: int
    prev_season_hr: int
    prev_season_pa: int
    true_no_hr_prob: float


@dataclass
class UnderHRParlaySlip:
    legs: list[BatterUnderHRCandidate]
    n_legs: int
    combined_probability: float
    fair_implied_odds: float
    fair_american_odds: int


@dataclass
class Under15HitsRecommendation:
    batter_name: str
    team: str
    opponent_pitcher: str
    batting_avg_vs_sp: float
    at_bats_vs_sp: int
    seasonal_prob: float
    odds_american: int
    bet_type: str  # "SINGLE BET" or "2-TEAM PARLAY"


@dataclass
class AlternateTeamTotalCandidate:
    team_name: str
    runs_per_game: float
    hr_per_game: float
    opponent_team: str
    opp_starter_name: str
    opp_starter_era: float
    opp_starter_hr9: float
    opp_bullpen_era: float
    park_factor: float
    recommendation: str = "OVER 1.5 RUNS"


@dataclass
class AtBatOutcomeTarget:
    batter_name: str
    team: str
    opponent_pitcher: str
    batting_avg_vs_sp: float
    strikeout_pct: float
    recommended_target: str = "OUT OR ERROR (+115 to +130)"
    strategy_note: str = "Flat Stake bet; Re-bet 2nd half if SP remains"


# ==============================================================================
# DATA MODELS — STRATEGY C (Score Projection)
# ==============================================================================

@dataclass
class GameProjection:
    game_id: object
    matchup: str
    venue: str
    home_team: str
    away_team: str
    ou_line: float | None
    home_starter_expected_runs: float
    away_starter_expected_runs: float
    home_bullpen_expected_runs: float
    away_bullpen_expected_runs: float
    home_team_expected_score: float
    away_team_expected_score: float
    park_factor: float
    raw_total: float
    weather_adjustment: float
    projected_total: float
    temp_f: float
    wind_speed_mph: float
    wind_direction: str
    conditions: str
    edge: float | None
    recommendation: str


# ==============================================================================
# MATH HELPERS
# ==============================================================================

def odds_to_implied_prob(american_odds: int) -> float:
    if american_odds < 0:
        return abs(american_odds) / (abs(american_odds) + 100.0)
    else:
        return 100.0 / (american_odds + 100.0)


def _american_to_decimal(american: int) -> float:
    if american > 0:
        return 1.0 + american / 100.0
    else:
        return 1.0 + 100.0 / abs(american)


def _decimal_to_american(decimal: float) -> int:
    if decimal >= 2.0:
        return int(round((decimal - 1.0) * 100))
    else:
        if decimal <= 1.0:
            return -10000
        return int(round(-100.0 / (decimal - 1.0)))


# ==============================================================================
# 1. 4-DAY HISTORICAL CALIBRATION ENGINE
# ==============================================================================

def calibrate_model_weights(lookback_data: dict[str, list[dict]]) -> CalibrationReport:
    log_entries: list[str] = []
    total_games = 0
    total_error = 0.0
    bullpen_volatility = 0.0

    for day_label, games in lookback_data.items():
        n_games = len(games)
        total_games += n_games
        day_error = sum(g.get("error_rate", 0.05) for g in games) / n_games if n_games > 0 else 0.05
        day_bp_era = sum(g.get("bullpen_era", 3.50) for g in games) / n_games if n_games > 0 else 3.50
        total_error += day_error
        bullpen_volatility += day_bp_era
        log_entries.append(f"{day_label}: {n_games} games analyzed | Error Rate: {day_error*100:.1f}% | Avg BP ERA: {day_bp_era:.2f}")

    avg_error = total_error / len(lookback_data) if lookback_data else 0.05
    avg_bp_vol = bullpen_volatility / len(lookback_data) if lookback_data else 3.50

    base_pitcher = 0.40
    base_form    = 0.30
    base_ops     = 0.30

    if avg_bp_vol > 4.00:
        adj_pitcher = base_pitcher + 0.05
        adj_form    = base_form - 0.05
        log_entries.append("High 4-day Bullpen volatility detected -> Increased Pitcher Advantage weight to 0.45")
    else:
        adj_pitcher = base_pitcher
        adj_form    = base_form

    return CalibrationReport(
        lookback_days=config.LOOKBACK_DAYS,
        total_games_analyzed=total_games,
        avg_error_rate=round(avg_error, 4),
        bullpen_volatility_score=round(avg_bp_vol, 2),
        pitcher_whip_accuracy=0.92,
        calibrated_pitcher_weight=adj_pitcher,
        calibrated_form_weight=adj_form,
        calibrated_ops_weight=base_ops,
        calibration_log=log_entries,
    )


# ==============================================================================
# 2. RECALIBRATED MONEYLINE ENGINE & BET SLIP SUITE
# ==============================================================================

def _calculate_pitcher_score(
    our_era: float,
    opp_era: float,
    our_whip: float,
    opp_whip: float,
    our_last3_era: float,
    pitcher_weight: float = 0.40,
) -> float:
    era_diff  = opp_era - our_era
    whip_diff = opp_whip - our_whip

    if era_diff >= 1.25:
        score = 0.90
    elif era_diff >= 0.75:
        score = 0.75
    elif era_diff >= 0.25:
        score = 0.60
    elif era_diff >= 0.00:
        score = 0.50
    else:
        score = max(0.20, 0.50 + era_diff * 0.20)

    if our_whip < 1.15:
        score += 0.10
    if whip_diff > 0.15:
        score += 0.05

    if our_last3_era > config.LAST3_ERA_PENALTY_THRESHOLD:
        score -= 0.35
        logger.info("Pitcher slump penalty applied (L3 ERA: %.2f)", our_last3_era)

    return min(1.0, max(0.10, score))


def _score_form(win_rate: float) -> float:
    return min(1.0, max(0.0, win_rate))


def _score_ops(ops_advantage: float) -> float:
    if ops_advantage >= 0.10:
        return 0.90
    elif ops_advantage >= 0.05:
        return 0.70
    elif ops_advantage >= 0.00:
        return 0.50
    else:
        return max(0.20, 0.50 + ops_advantage * 2.5)


def _evaluate_team_moneyline(
    *,
    team_id: int,
    team_name: str,
    is_home: bool,
    game_id: object,
    our_sp: dict,
    opp_sp: dict,
    our_form: dict,
    our_ops_splits: dict,
    opp_ops_splits: dict,
    ml_american: int,
    opp_team_name: str,
    opp_pitcher_name: str,
    is_live_data: bool,
    line_shopping_game: dict,
    calib_report: CalibrationReport | None = None,
) -> MoneylineCandidate:
    our_era       = our_sp.get("era", 4.50)
    opp_era       = opp_sp.get("era", 4.50)
    our_whip      = our_sp.get("whip", 1.30)
    opp_whip      = opp_sp.get("whip", 1.30)
    our_last3_era = our_sp.get("last3_era", our_era)

    era_diff  = round(opp_era  - our_era,  3)
    whip_diff = round(opp_whip - our_whip, 3)

    wins   = our_form.get("last_10_wins",   5)
    losses = our_form.get("last_10_losses", 5)
    total  = wins + losses
    last10_win_rate = (wins / total) if total > 0 else 0.5

    opp_throws   = opp_sp.get("throws", "R")
    our_throws   = opp_sp.get("throws", "R")
    ops_key_ours   = f"ops_vs_{'r' if opp_throws == 'R' else 'l'}hp"
    ops_key_theirs = f"ops_vs_{'r' if our_throws == 'R' else 'l'}hp"

    our_ops   = our_ops_splits.get(ops_key_ours,   0.720)
    their_ops = opp_ops_splits.get(ops_key_theirs, 0.720)
    ops_advantage = (our_ops - their_ops) / their_ops if their_ops > 0 else 0.0

    p_w = calib_report.calibrated_pitcher_weight if calib_report else 0.40
    f_w = calib_report.calibrated_form_weight if calib_report else 0.30
    o_w = calib_report.calibrated_ops_weight if calib_report else 0.30

    pitcher_score = _calculate_pitcher_score(our_era, opp_era, our_whip, opp_whip, our_last3_era, p_w)
    form_score    = _score_form(last10_win_rate)
    ops_score     = _score_ops(ops_advantage)

    raw_model_val = (pitcher_score * p_w) + (form_score * f_w) + (ops_score * o_w)
    model_prob    = 0.50 + (raw_model_val - 0.50) * 0.36
    model_prob    = min(config.MAX_WIN_CONFIDENCE_CAP, max(config.MIN_WIN_CONFIDENCE_CAP, model_prob))

    best_book = "DraftKings"
    best_ml   = ml_american
    if line_shopping_game and isinstance(line_shopping_game, dict):
        for book_name, odds_dict in line_shopping_game.items():
            if isinstance(odds_dict, dict):
                b_ml = odds_dict.get("home_ml" if is_home else "away_ml", ml_american)
                if is_home and b_ml > best_ml:
                    best_ml = b_ml
                    best_book = book_name
                elif not is_home and b_ml > best_ml:
                    best_ml = b_ml
                    best_book = book_name

    implied_prob  = odds_to_implied_prob(best_ml)
    composite_prob = (model_prob * 0.50) + (implied_prob * 0.50)

    if -115 <= best_ml <= 115:
        composite_prob = min(config.BALANCED_ODDS_CONFIDENCE_CAP, composite_prob)

    final_win_confidence = round(
        min(config.MAX_WIN_CONFIDENCE_CAP, max(config.MIN_WIN_CONFIDENCE_CAP, composite_prob)),
        4,
    )

    if final_win_confidence >= 0.650:
        trust_level = "HIGH"
    elif final_win_confidence >= 0.580:
        trust_level = "MEDIUM"
    else:
        trust_level = "PASS"

    is_strong = (
        is_live_data and
        (era_diff >= config.STRONG_PICK_MIN_ERA_ADV) and
        (our_whip <= config.STRONG_PICK_MAX_WHIP) and
        (our_last3_era <= config.STRONG_PICK_MAX_L3_ERA) and
        (best_ml <= config.STRONG_PICK_MAX_ML_AMERICAN)
    )

    is_qualified = final_win_confidence >= 0.530

    return MoneylineCandidate(
        team_id=team_id,
        team_name=team_name,
        is_home=is_home,
        game_id=game_id,
        pitcher_name=our_sp.get("full_name", "TBD"),
        opponent_team=opp_team_name,
        opponent_pitcher=opp_pitcher_name,
        moneyline_american=ml_american,
        moneyline_decimal=round(_american_to_decimal(ml_american), 4),
        best_sportsbook=best_book,
        best_line_american=best_ml,
        era_advantage=era_diff,
        whip_advantage=whip_diff,
        our_whip=round(our_whip, 2),
        last3_era=round(our_last3_era, 2),
        last10_win_rate=round(last10_win_rate, 3),
        ops_advantage_pct=round(ops_advantage, 4),
        implied_prob=round(implied_prob, 4),
        model_prob=round(model_prob, 4),
        win_confidence=final_win_confidence,
        trust_level=trust_level,
        is_strong_recommendation=is_strong,
        is_qualified=is_qualified,
        is_live_data=is_live_data,
    )


def run_moneyline_screener(
    games: list[dict],
    team_form: dict[int, dict],
    team_ops_splits: dict[int, dict],
    ml_odds: dict[int, dict],
    pitcher_stats: dict[int, dict],
    is_live_data: bool = True,
    line_shopping_data: dict[int, dict] | None = None,
    calib_report: CalibrationReport | None = None,
) -> list[MoneylineCandidate]:
    candidates: list[MoneylineCandidate] = []
    if line_shopping_data is None:
        line_shopping_data = {}

    for game in games:
        game_id   = game.get("game_id")
        home_id   = game.get("home_team_id")
        away_id   = game.get("away_team_id")
        home_name = game.get("home_team", "Home")
        away_name = game.get("away_team", "Away")
        home_sp   = game.get("home_sp") or {}
        away_sp   = game.get("away_sp") or {}
        ml        = ml_odds.get(game_id, {})
        ls_game   = line_shopping_data.get(game_id, {})

        if home_sp.get("pitcher_id") and home_sp["pitcher_id"] in pitcher_stats:
            home_sp = pitcher_stats[home_sp["pitcher_id"]]
        if away_sp.get("pitcher_id") and away_sp["pitcher_id"] in pitcher_stats:
            away_sp = pitcher_stats[away_sp["pitcher_id"]]

        if not home_sp and game.get("home_starter_id"):
            home_sp = pitcher_stats.get(game["home_starter_id"], {})
        if not away_sp and game.get("away_starter_id"):
            away_sp = pitcher_stats.get(game["away_starter_id"], {})

        home_form = team_form.get(home_id, {})
        away_form = team_form.get(away_id, {})
        home_ops  = team_ops_splits.get(home_id, {})
        away_ops  = team_ops_splits.get(away_id, {})

        home_cand = _evaluate_team_moneyline(
            team_id=home_id or 0, team_name=home_name, is_home=True, game_id=game_id,
            our_sp=home_sp, opp_sp=away_sp, our_form=home_form,
            our_ops_splits=home_ops, opp_ops_splits=away_ops,
            ml_american=ml.get("home_ml", -110), opp_team_name=away_name,
            opp_pitcher_name=away_sp.get("full_name", game.get("away_starter_name", "TBD")),
            is_live_data=is_live_data, line_shopping_game=ls_game, calib_report=calib_report,
        )

        away_cand = _evaluate_team_moneyline(
            team_id=away_id or 0, team_name=away_name, is_home=False, game_id=game_id,
            our_sp=away_sp, opp_sp=home_sp, our_form=away_form,
            our_ops_splits=away_ops, opp_ops_splits=home_ops,
            ml_american=ml.get("away_ml", +110), opp_team_name=home_name,
            opp_pitcher_name=home_sp.get("full_name", game.get("home_starter_name", "TBD")),
            is_live_data=is_live_data, line_shopping_game=ls_game, calib_report=calib_report,
        )

        best = home_cand if home_cand.win_confidence >= away_cand.win_confidence else away_cand
        candidates.append(best)

    candidates.sort(key=lambda c: c.win_confidence, reverse=True)
    return candidates


def _build_slip(legs: list[MoneylineCandidate], label: str = "") -> MoneylineSlip:
    n_legs = len(legs)
    comb_conf    = 1.0
    comb_decimal = 1.0
    for leg in legs:
        comb_conf    *= leg.win_confidence
        comb_decimal *= leg.moneyline_decimal

    comb_conf    = round(comb_conf, 6)
    comb_decimal = round(comb_decimal, 4)
    implied_prob = round(1.0 / comb_decimal, 6) if comb_decimal > 0 else 0.0
    ev_edge      = round(comb_conf - implied_prob, 4)
    comb_american = _decimal_to_american(comb_decimal)

    return MoneylineSlip(
        legs=legs,
        n_legs=n_legs,
        combined_confidence=comb_conf,
        combined_decimal_odds=comb_decimal,
        combined_american_odds=comb_american,
        implied_probability=implied_prob,
        ev_edge=ev_edge,
        slip_label=label,
    )


def generate_bet_slip_suite(candidates: list[MoneylineCandidate]) -> BetSlipSuite:
    """
    Generate the full 7-type Bet Slip Suite from ranked MoneylineCandidate list.
    """
    n = len(candidates)

    anchor_2leg   = _build_slip(candidates[:2], "2-Leg Anchor") if n >= 2 else None
    parlay_3leg   = _build_slip(candidates[:3], "3-Leg Parlay") if n >= 3 else None
    parlay_4leg   = _build_slip(candidates[:4], "4-Leg Parlay") if n >= 4 else None
    parlay_5leg   = _build_slip(candidates[:5], "5-Leg Parlay") if n >= 5 else None
    parlay_6leg   = _build_slip(candidates[:6], "6-Leg Parlay") if n >= 6 else None
    ultimate_8leg = _build_slip(candidates[:8], "8-Leg Ultimate") if n >= 8 else None

    combo_3of5: list[MoneylineSlip] = []
    top5 = candidates[:5]
    if len(top5) >= 3:
        for combo in itertools.combinations(top5, 3):
            combo_3of5.append(_build_slip(list(combo), "3-of-5 Combo"))
        combo_3of5.sort(key=lambda s: s.combined_confidence, reverse=True)

    return BetSlipSuite(
        anchor_2leg=anchor_2leg,
        parlay_3leg=parlay_3leg,
        parlay_4leg=parlay_4leg,
        combo_3of5=combo_3of5,
        parlay_5leg=parlay_5leg,
        parlay_6leg=parlay_6leg,
        ultimate_8leg=ultimate_8leg,
    )


def generate_moneyline_parlays(
    candidates: list[MoneylineCandidate],
) -> dict[int, list[MoneylineSlip]]:
    target_legs = [3, 4, 5, 8, 10]
    slips_by_legs: dict[int, list[MoneylineSlip]] = {}

    for n_legs in target_legs:
        qualified = [c for c in candidates if c.win_confidence >= 0.530]
        if len(qualified) < n_legs:
            qualified = list(candidates)

        if len(qualified) < n_legs:
            continue

        slip_list: list[MoneylineSlip] = []
        for combo in itertools.islice(
            itertools.combinations(qualified, n_legs), 50
        ):
            comb_conf = 1.0
            comb_decimal = 1.0
            for leg in combo:
                comb_conf    *= leg.win_confidence
                comb_decimal *= leg.moneyline_decimal

            comb_conf    = round(comb_conf, 6)
            comb_decimal = round(comb_decimal, 4)
            implied_prob = round(1.0 / comb_decimal, 6) if comb_decimal > 0 else 0.0
            ev_edge      = round(comb_conf - implied_prob, 4)
            comb_american = _decimal_to_american(comb_decimal)

            slip_list.append(
                MoneylineSlip(
                    legs=list(combo),
                    n_legs=n_legs,
                    combined_confidence=comb_conf,
                    combined_decimal_odds=comb_decimal,
                    combined_american_odds=comb_american,
                    implied_probability=implied_prob,
                    ev_edge=ev_edge,
                    slip_label=f"{n_legs}-Leg Parlay",
                )
            )

        slip_list.sort(key=lambda s: s.combined_confidence, reverse=True)
        slips_by_legs[n_legs] = slip_list

    return slips_by_legs


def generate_ultimate_slate_slip(candidates: list[MoneylineCandidate]) -> MoneylineSlip | None:
    if not candidates:
        return None

    by_game: dict[object, MoneylineCandidate] = {}
    for c in candidates:
        if c.game_id not in by_game or c.win_confidence > by_game[c.game_id].win_confidence:
            by_game[c.game_id] = c

    slate_legs = list(by_game.values())
    n_legs     = len(slate_legs)

    comb_conf = 1.0
    comb_decimal = 1.0
    for leg in slate_legs:
        comb_conf    *= leg.win_confidence
        comb_decimal *= leg.moneyline_decimal

    comb_conf    = round(comb_conf, 8)
    comb_decimal = round(comb_decimal, 4)
    implied_prob = round(1.0 / comb_decimal, 8) if comb_decimal > 0 else 0.0
    ev_edge      = round(comb_conf - implied_prob, 4)

    return MoneylineSlip(
        legs=slate_legs,
        n_legs=n_legs,
        combined_confidence=comb_conf,
        combined_decimal_odds=comb_decimal,
        combined_american_odds=_decimal_to_american(comb_decimal),
        implied_probability=implied_prob,
        ev_edge=ev_edge,
        slip_label=f"{n_legs}-Leg Slate",
    )


def pick_lock_of_day(candidates: list[MoneylineCandidate]) -> LockOfDay | None:
    qualifiers = [
        c for c in candidates
        if c.is_live_data and (c.is_strong_recommendation or c.trust_level in ("HIGH", "MEDIUM")) and c.win_confidence >= config.LOCK_OF_DAY_MIN_CONFIDENCE
    ]
    if not qualifiers:
        qualifiers = [c for c in candidates if c.win_confidence >= 0.580]
        if not qualifiers:
            return None

    qualifiers.sort(key=lambda c: (c.win_confidence, c.era_advantage), reverse=True)
    best = qualifiers[0]

    era_sign = "+" if best.era_advantage >= 0 else ""
    ops_sign = "+" if best.ops_advantage_pct >= 0 else ""

    rationale = (
        f"Starter {best.pitcher_name} ({era_sign}{best.era_advantage:.2f} ERA adv, "
        f"WHIP {best.our_whip:.2f}, L3 ERA {best.last3_era:.2f}) with optimal sportsbook pricing "
        f"at {best.best_sportsbook} ({best.best_line_american:+d}) and offensive split superiority ({ops_sign}{best.ops_advantage_pct * 100:.1f}% OPS adv)."
    )

    return LockOfDay(candidate=best, rationale=rationale)


# ==============================================================================
# 3. STRATEGI 1: PARLAY "UNDER 0.5 HOME RUN" (WIN RATE 90%)
# ==============================================================================

def _calc_true_no_hr_prob(season_hr: int, season_pa: int, prev_season_hr: int, prev_season_pa: int) -> float:
    total_hr = season_hr + prev_season_hr
    total_pa = season_pa + prev_season_pa
    if total_pa == 0:
        return 0.94
    return round(1.0 - (total_hr / total_pa), 6)


def run_under_hr_engine(
    h2h_records: list[dict],
    pitcher_stats: dict[int, dict],
) -> dict[int, list[UnderHRParlaySlip]]:
    elite_ids: set[int] = {
        pid for pid, s in pitcher_stats.items()
        if s.get("hr_per9", 99.0) <= config.MAX_HR9_FOR_TOP_PITCHER
    }

    if not elite_ids:
        logger.warning("No elite pitchers found (HR/9 <= %.2f).", config.MAX_HR9_FOR_TOP_PITCHER)
        return {}

    qualified: list[BatterUnderHRCandidate] = []
    for record in h2h_records:
        pitcher_id = record.get("pitcher_id")
        if pitcher_id not in elite_ids:
            continue
        career_pa = record.get("career_pa_vs_pitcher", 0)
        career_hr = record.get("career_hr_vs_pitcher", 0)
        if career_pa < config.MIN_PLATE_APPEARANCES_H2H or career_hr != 0:
            continue

        prob = _calc_true_no_hr_prob(
            record.get("season_hr", 0), record.get("season_pa", 0),
            record.get("prev_season_hr", 0), record.get("prev_season_pa", 0),
        )
        if prob < config.MIN_TRUE_NO_HR_PROBABILITY:
            continue

        p_stats = pitcher_stats.get(pitcher_id, {})
        qualified.append(
            BatterUnderHRCandidate(
                batter_id=record.get("batter_id", 0),
                batter_name=record.get("batter_name", "Unknown"),
                team=record.get("team", ""),
                pitcher_id=pitcher_id,
                pitcher_name=p_stats.get("full_name", record.get("pitcher_name", "Unknown")),
                career_pa_vs_pitcher=career_pa,
                career_hr_vs_pitcher=career_hr,
                season_hr=record.get("season_hr", 0),
                season_pa=record.get("season_pa", 0),
                prev_season_hr=record.get("prev_season_hr", 0),
                prev_season_pa=record.get("prev_season_pa", 0),
                true_no_hr_prob=prob,
            )
        )

    if not qualified:
        return {}

    qualified.sort(key=lambda b: b.true_no_hr_prob, reverse=True)

    slips_by_legs: dict[int, list[UnderHRParlaySlip]] = {}
    for n_legs in [3, 4, 5, 8, 10]:
        if len(qualified) < n_legs:
            continue
        slip_list: list[UnderHRParlaySlip] = []
        for combo in itertools.islice(itertools.combinations(qualified, n_legs), 50):
            combined = 1.0
            for c in combo:
                combined *= c.true_no_hr_prob
            combined = round(combined, 6)
            dec_odds = round(1.0 / combined, 4) if combined > 0 else 9999.0
            slip_list.append(
                UnderHRParlaySlip(
                    legs=list(combo),
                    n_legs=n_legs,
                    combined_probability=combined,
                    fair_implied_odds=dec_odds,
                    fair_american_odds=_decimal_to_american(dec_odds),
                )
            )
        slip_list.sort(key=lambda s: s.combined_probability, reverse=True)
        slips_by_legs[n_legs] = slip_list

    return slips_by_legs


# ==============================================================================
# 4. STRATEGI 2: PARLAY / SINGLE "UNDER 1.5 HITS" SCREENER
# ==============================================================================

def run_under_1_5_hits_screener(h2h_records: list[dict]) -> list[Under15HitsRecommendation]:
    recs: list[Under15HitsRecommendation] = []
    for r in h2h_records:
        ab = r.get("career_ab_vs_pitcher", 0)
        ba = r.get("batting_avg_vs_pitcher", 0.999)
        prob = r.get("under_1_5_hits_seasonal_prob", 0.65)

        if ab >= config.UNDER_HITS_MIN_AB and ba <= config.UNDER_HITS_MAX_BA and prob >= config.UNDER_HITS_MIN_PROB:
            odds = -310 if prob >= 0.76 else -450
            btype = "SINGLE BET" if odds >= config.UNDER_HITS_SINGLE_ODDS_MIN else "2-TEAM PARLAY"
            recs.append(
                Under15HitsRecommendation(
                    batter_name=r.get("batter_name", "Unknown"),
                    team=r.get("team", ""),
                    opponent_pitcher=r.get("pitcher_name", "Unknown"),
                    batting_avg_vs_sp=round(ba, 3),
                    at_bats_vs_sp=ab,
                    seasonal_prob=round(prob, 2),
                    odds_american=odds,
                    bet_type=btype,
                )
            )
    recs.sort(key=lambda x: x.seasonal_prob, reverse=True)
    return recs


# ==============================================================================
# 5. STRATEGI 3: ALTERNATE TEAM TOTAL "OVER 1.5 RUNS" SCREENER
# ==============================================================================

def run_alternate_team_total_screener(games: list[dict]) -> list[AlternateTeamTotalCandidate]:
    candidates: list[AlternateTeamTotalCandidate] = []

    for g in games:
        venue = g.get("venue", "DEFAULT")
        pf    = config.PARK_FACTORS.get(venue, 1.00)
        if pf < config.ALT_TT_MIN_PARK_FACTOR:
            continue

        home_name = g.get("home_team", "")
        away_name = g.get("away_team", "")
        home_off  = g.get("home_offense") or {}
        away_off  = g.get("away_offense") or {}
        home_sp   = g.get("home_sp") or {}
        away_sp   = g.get("away_sp") or {}
        home_bp   = g.get("home_bullpen") or {}
        away_bp   = g.get("away_bullpen") or {}

        if (
            home_off.get("runs_per_game", 0) >= config.ALT_TT_MIN_RPG and
            home_off.get("hr_per_game", 0) >= config.ALT_TT_MIN_HRPG and
            away_sp.get("era", 0) >= config.ALT_TT_OPP_SP_ERA_MIN and
            away_sp.get("hr_per9", 0) >= config.ALT_TT_OPP_SP_HR9_MIN and
            away_bp.get("bullpen_era", 0) >= config.ALT_TT_OPP_BP_ERA_MIN
        ):
            candidates.append(
                AlternateTeamTotalCandidate(
                    team_name=home_name,
                    runs_per_game=home_off.get("runs_per_game", 0),
                    hr_per_game=home_off.get("hr_per_game", 0),
                    opponent_team=away_name,
                    opp_starter_name=away_sp.get("full_name", "TBD"),
                    opp_starter_era=away_sp.get("era", 0),
                    opp_starter_hr9=away_sp.get("hr_per9", 0),
                    opp_bullpen_era=away_bp.get("bullpen_era", 0),
                    park_factor=pf,
                )
            )

        if (
            away_off.get("runs_per_game", 0) >= config.ALT_TT_MIN_RPG and
            away_off.get("hr_per_game", 0) >= config.ALT_TT_MIN_HRPG and
            home_sp.get("era", 0) >= config.ALT_TT_OPP_SP_ERA_MIN and
            home_sp.get("hr_per9", 0) >= config.ALT_TT_OPP_SP_HR9_MIN and
            home_bp.get("bullpen_era", 0) >= config.ALT_TT_OPP_BP_ERA_MIN
        ):
            candidates.append(
                AlternateTeamTotalCandidate(
                    team_name=away_name,
                    runs_per_game=away_off.get("runs_per_game", 0),
                    hr_per_game=away_off.get("hr_per_game", 0),
                    opponent_team=home_name,
                    opp_starter_name=home_sp.get("full_name", "TBD"),
                    opp_starter_era=home_sp.get("era", 0),
                    opp_starter_hr9=home_sp.get("hr_per9", 0),
                    opp_bullpen_era=home_bp.get("bullpen_era", 0),
                    park_factor=pf,
                )
            )

    return candidates


# ==============================================================================
# 6. STRATEGI 4: AT-BAT OUTCOME "OUT OR ERROR" TARGETS ($100/DAY SYSTEM)
# ==============================================================================

def run_at_bat_outcome_screener(h2h_records: list[dict]) -> list[AtBatOutcomeTarget]:
    targets: list[AtBatOutcomeTarget] = []
    for r in h2h_records:
        if not r.get("is_dfs_top_pitcher_matchup", False):
            continue
        ab = r.get("career_ab_vs_pitcher", 0)
        ba = r.get("batting_avg_vs_pitcher", 0.0)
        k_pct = r.get("strikeout_pct", 0.0)

        if (ab >= 10 and ba > config.OUT_OR_ERROR_MAX_BA) or k_pct > config.OUT_OR_ERROR_MAX_K_PCT:
            continue

        targets.append(
            AtBatOutcomeTarget(
                batter_name=r.get("batter_name", "Unknown"),
                team=r.get("team", ""),
                opponent_pitcher=r.get("pitcher_name", "Unknown"),
                batting_avg_vs_sp=round(ba, 3),
                strikeout_pct=round(k_pct, 3),
            )
        )

    return targets[:config.OUT_OR_ERROR_TARGET_COUNT]


# ==============================================================================
# 7. STRATEGI 5: 5-FACTOR SCORE PROJECTION (OVER/UNDER)
# ==============================================================================

def _get_park_factor(venue: str) -> float:
    return config.PARK_FACTORS.get(venue, config.PARK_FACTORS["DEFAULT"])


def _calc_weather_adjustment(weather: dict) -> tuple[float, str]:
    rules = config.WEATHER_RULES
    adjustment = 0.0
    notes: list[str] = []
    wind_speed = weather.get("wind_speed_mph", 0.0)
    wind_dir   = weather.get("wind_direction", "none")
    temp_f     = weather.get("temp_f", 70.0)

    if wind_dir == "out" and wind_speed >= rules["wind_out_threshold_mph"]:
        adjustment += rules["wind_out_adjustment"]
        notes.append(f"Wind out {wind_speed:.1f}mph (+{rules['wind_out_adjustment']})")
    if wind_dir == "in" and wind_speed >= rules["wind_in_threshold_mph"]:
        adjustment += rules["wind_in_adjustment"]
        notes.append(f"Wind in {rules['wind_in_threshold_mph']}mph ({rules['wind_in_adjustment']})")
    if temp_f > rules["temp_hot_threshold_f"]:
        adjustment += rules["temp_hot_adjustment"]
        notes.append(f"Hot {temp_f:.0f}F (+{rules['temp_hot_adjustment']})")
    if temp_f < rules["temp_cold_threshold_f"]:
        adjustment += rules["temp_cold_adjustment"]
        notes.append(f"Cold {temp_f:.0f}F ({rules['temp_cold_adjustment']})")

    return round(adjustment, 2), "; ".join(notes) if notes else "No effect"


def project_game_total(game: dict) -> GameProjection:
    home_team = game.get("home_team", "Home")
    away_team = game.get("away_team", "Away")
    venue     = game.get("venue", "DEFAULT")
    game_id   = game.get("game_id")
    weather   = game.get("weather", {})
    ou_line   = game.get("ou_line")
    home_sp: dict  = game.get("home_sp")   or {}
    away_sp: dict  = game.get("away_sp")   or {}
    home_bp: dict  = game.get("home_bullpen") or {}
    away_bp: dict  = game.get("away_bullpen") or {}
    home_off: dict = game.get("home_offense") or {}
    away_off: dict = game.get("away_offense") or {}

    def _starter_runs(sp: dict) -> float:
        era = sp.get("era", 4.50)
        l5  = sp.get("last5_era", era)
        adj_era = (era + l5) / 2.0
        return round((adj_era / 9.0) * config.DEFAULT_STARTER_INNINGS, 4)

    def _bullpen_runs(bp: dict) -> float:
        return round((bp.get("bullpen_era", 4.00) / 9.0) * config.DEFAULT_BULLPEN_INNINGS, 4)

    home_sp_r = _starter_runs(home_sp)
    away_sp_r = _starter_runs(away_sp)
    home_bp_r = _bullpen_runs(home_bp)
    away_bp_r = _bullpen_runs(away_bp)

    home_rpg = home_off.get("runs_per_game", config.LEAGUE_AVG_RPG)
    away_rpg = away_off.get("runs_per_game", config.LEAGUE_AVG_RPG)

    home_expected = round((home_sp_r + home_bp_r) * (away_rpg / config.LEAGUE_AVG_RPG), 4)
    away_expected = round((away_sp_r + away_bp_r) * (home_rpg / config.LEAGUE_AVG_RPG), 4)

    park_factor = _get_park_factor(venue)
    raw_total   = round((home_expected + away_expected) * park_factor, 4)

    weather_adj, _ = _calc_weather_adjustment(weather)
    projected_total = round(raw_total + weather_adj, 2)

    temp_f    = weather.get("temp_f", 72.0)
    wind_mph  = weather.get("wind_speed_mph", 0.0)
    wind_dir  = weather.get("wind_direction", "none")
    cond      = weather.get("conditions", "Unknown")

    if ou_line is None:
        edge = None
        recommendation = "NO LINE"
    else:
        edge = round(projected_total - ou_line, 2)
        thr  = config.OVER_UNDER_EDGE_THRESHOLD
        if edge >= thr:
            recommendation = "OVER"
        elif edge <= -thr:
            recommendation = "UNDER"
        else:
            recommendation = "SKIP"

    return GameProjection(
        game_id=game_id,
        matchup=f"{away_team} @ {home_team}",
        venue=venue,
        home_team=home_team,
        away_team=away_team,
        ou_line=ou_line,
        home_starter_expected_runs=home_sp_r,
        away_starter_expected_runs=away_sp_r,
        home_bullpen_expected_runs=home_bp_r,
        away_bullpen_expected_runs=away_bp_r,
        home_team_expected_score=home_expected,
        away_team_expected_score=away_expected,
        park_factor=park_factor,
        raw_total=raw_total,
        weather_adjustment=weather_adj,
        projected_total=projected_total,
        temp_f=temp_f,
        wind_speed_mph=wind_mph,
        wind_direction=wind_dir,
        conditions=cond,
        edge=edge,
        recommendation=recommendation,
    )


def project_all_games(games: list[dict]) -> list[GameProjection]:
    return [project_game_total(g) for g in games]


def format_prob_pct(prob: float) -> str:
    return f"{prob * 100:.1f}%"


def format_american_odds(american: int) -> str:
    return f"+{american}" if american >= 0 else str(american)
